Repository AirSkyBoat/AirSkyBoat, pull requests merged in 2022-08, with the labels that each got.

#252 Add Missing isFacing() Check to CMeleeRatio
  scripts/globals/weaponskills.lua
  src/map/utils/battleutils.cpp
Labels: Squash, Sanity Fail (Old Style)

#256 Fix Hit Rate Calculations | Cleanup Dyna Stuff | Make Dynamic Renamer Work
  modules/era/lua_dynamis/globals/era_dynamis.lua
  modules/renamer/cpp/renamer.cpp
  scripts/globals/weaponskills.lua
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
Labels: Squash

#257 Era module to prevent entering Mog Garden
  modules/era/cpp/disable_mog_garden.cpp
Labels: Approved Pending Changes
